### ISSUE TITLE
Wikipedia plug-in not working

### ISSUE THREAD

**Issue by menismu** [menismu/popcorn-js#56]
Issue reported: [https://github.com/mozilla/popcorn-js/issues/464](https://github.com/mozilla/popcorn-js/issues/464)
Reported by: @staplegun 

The Wikipedia plug-in isn't displaying the content when called via a parseJSON events data file.

The Wikipedia response contains a warning that 'props' is an unrecognised parameter. When I changed it to the correct 'prop' parameter, the 'parse.displaytitle' field disappeared from the Wikipedia response, however 'parse.title' is still included.

**Comment by titaniumbones** [comment]
I'm not able to replicate this issue myself, and I think the MediaWiki API may now alias `props` to `prop`. In any case, this one-character fix is harmless & *should* fix this if it's stil lan issue.
