### ISSUE TITLE
repo appears to be abandoned

### ISSUE THREAD

**Issue by titaniumbones** [menismu/popcorn-js#80]
@menismu has not been active on Github for about 6 months; this fork appears to be abandoned. As the project suffers quite a bit from bitrot (esp related to external API's and somewhat outdated CSS), it may not be worth reviving.

**Comment by menismu** [comment]
@titaniumbones First of all thanks for your great effort in the pull requests you have submitted, I just merged them into the project. I have also seen your Issues reported and I am planning to define a bit better the next version, I will appreciate all your help working on this project.

**Comment by titaniumbones** [comment]
Thanks for the pulls, and I'm looking forward to working on this together!
